FROM jupyterhub/jupyterhub:latest
WORKDIR /srv/jupyterhub
RUN apt-get update -y && \
    python3 -m pip install --no-cache-dir \
    dockerspawner \
    jupyterhub-nativeauthenticator
COPY jupyterhub_config.py /srv/jupyterhub/jupyterhub_config.py
CMD ["jupyterhub", "-f", "/srv/jupyterhub/jupyterhub_config.py"]
