# Используем базовый образ
FROM jupyter/scipy-notebook

# Исправляем права доступа для /var/lib/apt
RUN fix-permissions /var/lib/apt

# Используем базовый образ
FROM jupyter/scipy-notebook:latest

# Временно переключаемся на пользователя root для установки пакетов
USER root

# Устанавливаем Java 11
RUN apt-get update && \
    apt-get install -y openjdk-11-jdk && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Копируем requirements.txt в контейнер
COPY requirements.txt /tmp/requirements.txt

# Устанавливаем дополнительные Python-пакеты
RUN pip install --no-cache-dir -r /tmp/requirements.txt && \
    rm /tmp/requirements.txt

    # Возвращаемся к пользователю jovyan
USER jovyan
# Проверяем установку Java
RUN java -version

# Устанавливаем переменную окружения JAVA_HOME
ENV JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
ENV PATH=$JAVA_HOME/bin:$PATH

# Установка прав доступа для домашней директории jovyan
RUN fix-permissions /home/jovyan

