# Используем базовый образ
FROM jupyter/scipy-notebook

# Исправляем права доступа для /var/lib/apt
RUN fix-permissions /var/lib/apt

# Используем базовый образ
FROM jupyter/scipy-notebook:latest

# Временно переключаемся на пользователя root для установки пакетов
USER root

# Устанавливаем Java 11
RUN apt-get update && \
    apt-get install -y openjdk-11-jdk && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Копируем requirements.txt в контейнер
COPY requirements.txt /tmp/requirements.txt

# Устанавливаем дополнительные Python-пакеты
RUN pip install --no-cache-dir -r /tmp/requirements.txt && \
    rm /tmp/requirements.txt

    # Возвращаемся к пользователю jovyan
USER jovyan
# Проверяем установку Java
RUN java -version

# Устанавливаем переменную окружения JAVA_HOME
ENV JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
ENV PATH=$JAVA_HOME/bin:$PATH

# Установка прав доступа для домашней директории jovyan
RUN fix-permissions /home/jovyan

# Добавляем пользователя jovyan в sudoers (если нужно)
# RUN echo "jovyan ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
# USER ${NB_UID}

# Запуск JupyterLab
# CMD ["jupyter", "lab", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root"]
# Настройки JupyterLab
# COPY jupyter_notebook_config.py /etc/jupyter/
# Создаем пользователя jovyan
# ARG NB_USER=jovyan
# ARG NB_UID=1000
# ARG NB_GID=1001  # Используем другой GID

# RUN groupadd -g ${NB_GID} ${NB_USER} && \
#     useradd -u ${NB_UID} -g ${NB_GID} -m -s /bin/bash ${NB_USER} && \
#     echo "${NB_USER} ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers  
# # Переключаемся на пользователя jovyan
# USER ${NB_USER}

# Запускаем JupyterLab
# CMD ["jupyter", "lab", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root"]